name: Dummy Workflow
run-name: ${{ github.ref_name }} (${{github.ref_type}}, triggered by ${{ github.event_name }})

on:
  workflow_dispatch:
  push:
    branches:
      # Run on every branch
      - '**'
      # Except branches beginning with:
      - '!fail/**'
      - '!dead-end/**'
      - '!trash/**'
      - '!dependabot/**'  # avoid running Workflow twice, because Dependabot creates a branch ("push" event) and a pull request)
    tags:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dummy Echo
        run: |
          echo Möp
      # simulate a failing/succeeding build
      - name: Dummy Build
        run: |
          if grep -q "yes" should-fail; then
            exit 1
          fi
