name: Dummy Workflow
run-name: ${{ github.ref_name }} (${{github.ref_type}}, triggered by ${{ github.event_name }})

on:
  workflow_dispatch:
  push:
    branches:
      # Run on every branch
      - '**'
      # Except branches beginning with:
      - '!fail/**'
      - '!dead-end/**'
      - '!trash/**'
      - '!dependabot/**'  # avoid running Workflow twice, because Dependabot creates a branch ("push" event) and a pull request)
    tags:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dummy Echo
        run: |
          echo Möp
      # simulate a failing/succeeding build
      - name: Dummy Build
        run: |
          if grep -q "yes" should-fail; then
            exit 1
          fi
      - name: Dummy Deployment
        if: github.event_name != 'pull_request'
        run: |
          echo "Stuff has been deployed"

  dependabot-auto-merge:
    needs: dummy
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Using GITHUB_TOKEN __won't__ trigger following Workflows
          # see: https://github.com/orgs/community/discussions/55906
          #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
